/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.ControlPanelDAO;
import database.ProgramDAO;
import database.SprinklerDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ControlPanel;
import model.Program;
import model.Sprinkler;
import model.TimedSprinkler;

/**
 *
 * @author palmyman
 */
public class ProgramEditorDialog extends javax.swing.JDialog {

    private List<Program> programs;
    private int programId;
    private int sprinklerId;
    private SprinklerTableModel sprinklerTableModel;
    private List<ControlPanel> panels;
    private int panelId;

    /**
     * Creates new form NewProgramDialog
     */
    public ProgramEditorDialog() {
        initComponents();
        fillProgramComboBox();
        fillPanelComboBox();
        sprinklerTable.setModel(sprinklerTableModel = new SprinklerTableModel());        
    }

    private void fillProgramComboBox() {
        try {
            programs = new ArrayList<>(ProgramDAO.getInstance().getAll());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        programComboBox.removeAllItems();
        for (int i = 0; i < programs.size(); i++) {
            programComboBox.addItem(programs.get(i));
        }
    }

    private void fillPanelComboBox() {
        try {
            panels = new ArrayList<>(ControlPanelDAO.getInstance().getAll());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        panelComboBox.removeAllItems();
        for (int i = 0; i < panels.size(); i++) {
            panelComboBox.addItem(panels.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rescheduleButton = new javax.swing.JButton();
        dateValue = new com.toedter.calendar.JDateChooser();
        timeValue = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        programComboBox = new javax.swing.JComboBox();
        selectButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        indexValue = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        panelComboBox = new javax.swing.JComboBox();
        deleteSprinklerButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sprinklerTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        durationValue = new javax.swing.JSpinner();
        deleteProgramButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Program Editor");

        jLabel2.setText("Date:");

        jLabel3.setText("Time:");

        rescheduleButton.setText("Reschedule");
        rescheduleButton.setEnabled(false);
        rescheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescheduleButtonActionPerformed(evt);
            }
        });

        dateValue.setDateFormatString("yyyy-MM-dd");

        timeValue.setModel(new javax.swing.SpinnerDateModel());
        timeValue.setEditor(new javax.swing.JSpinner.DateEditor(timeValue, "HH:mm:ss"));

        jLabel4.setText("Program:");

        programComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Index:");

        indexValue.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel5.setText("Control Panel:");

        panelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deleteSprinklerButton.setText("Delete Sprinkler");
        deleteSprinklerButton.setEnabled(false);
        deleteSprinklerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSprinklerButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        sprinklerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sprinklerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sprinklerTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(sprinklerTable);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Schedule:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Sprinkler:");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Duration:");

        durationValue.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(10), null, Integer.valueOf(5)));

        deleteProgramButton.setText("Delete Program");
        deleteProgramButton.setEnabled(false);
        deleteProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProgramButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(programComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectButton)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(timeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rescheduleButton))
                                        .addComponent(dateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(252, 252, 252)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(durationValue, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(indexValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteProgramButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSprinklerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(programComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(timeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(rescheduleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(panelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(indexValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(durationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(deleteSprinklerButton)
                    .addComponent(deleteProgramButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rescheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescheduleButtonActionPerformed
        Program program = new Program(
                programId,
                null,
                new java.sql.Date(this.dateValue.getDate().getTime()),
                new java.sql.Time(((java.util.Date) this.timeValue.getValue()).getTime()));
        try {
            ProgramDAO.getInstance().update(program);
        } catch (SQLException ex) {
            Logger.getLogger(ProgramEditorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_rescheduleButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        addButton.setEnabled(true);
        rescheduleButton.setEnabled(true);
        deleteProgramButton.setEnabled(true);
        deleteSprinklerButton.setEnabled(false);
        dateValue.setDate(((Program) programComboBox.getSelectedItem()).getDate());
        timeValue.setValue(((Program) programComboBox.getSelectedItem()).getTime());
        programId = ((Program) programComboBox.getSelectedItem()).getId();
        this.sprinklerTableModel.refresh(programId);
    }//GEN-LAST:event_selectButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        int panelId = ((ControlPanel) panelComboBox.getSelectedItem()).getId();
        int index = (Integer) indexValue.getValue();
        int time = (Integer) durationValue.getValue();
        TimedSprinkler sprinkler = new TimedSprinkler(new Sprinkler(index, panelId), 0, programId, time);
        try {
            SprinklerDAO.getInstance().create(sprinkler);
        } catch (SQLException ex) {
            Logger.getLogger(NewPanelDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.sprinklerTableModel.refresh(programId);
    }//GEN-LAST:event_addButtonActionPerformed

    private void sprinklerTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sprinklerTableMouseReleased
        int row = sprinklerTable.getSelectedRow();
        sprinklerId = (Integer) sprinklerTable.getModel().getValueAt(row, 3);
        deleteSprinklerButton.setEnabled(true);
    }//GEN-LAST:event_sprinklerTableMouseReleased

    private void deleteSprinklerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSprinklerButtonActionPerformed
        try {
            SprinklerDAO.getInstance().delete(sprinklerId);
        } catch (SQLException ex) {
            Logger.getLogger(NewPanelDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.sprinklerTableModel.refresh(programId);
    }//GEN-LAST:event_deleteSprinklerButtonActionPerformed

    private void deleteProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProgramButtonActionPerformed
        try {
            ProgramDAO.getInstance().delete(programId);
        } catch (SQLException ex) {
            Logger.getLogger(NewPanelDialog.class.getName()).log(Level.SEVERE, null, ex);
        }        
        this.dispose();
    }//GEN-LAST:event_deleteProgramButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton closeButton;
    private com.toedter.calendar.JDateChooser dateValue;
    private javax.swing.JButton deleteProgramButton;
    private javax.swing.JButton deleteSprinklerButton;
    private javax.swing.JSpinner durationValue;
    private javax.swing.JSpinner indexValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox panelComboBox;
    private javax.swing.JComboBox programComboBox;
    private javax.swing.JButton rescheduleButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JTable sprinklerTable;
    private javax.swing.JSpinner timeValue;
    // End of variables declaration//GEN-END:variables
}
